services:

  mysql:
    image: mysql:8.4
    container_name: shopease-mysql
    environment:
      MYSQL_DATABASE: shopping_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      
    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s


  backend:
    image: shopease-backend:latest
    container_name: shopease-backend

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopping_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}


      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}

    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql_data: